### ISSUE TITLE
[BUG] Unable to finish installation

### ISSUE THREAD

**Issue by rastrof** [The-Animonculory/AVO#10]
I am unable to finish the installation of the modpack. I have tried several times to rerun wabbajack

Iit seems to remain stuck trying to find the right hash-version of the mod manager. Screenshot attached

![afbeelding](https://github.com/The-Animonculory/AVO/assets/169951/d6141111-9a09-43c9-b1bc-ca3746010dd9)

**Comment by Styyx1** [comment]
try a VPN or something. those files are on GitHub so it can only be a connection issue

**Comment by rastrof** [comment]
downloading manually worked
