### ISSUE TITLE
Dark Brotherhood armors[BUG]

### ISSUE THREAD

**Issue by ellis84** [The-Animonculory/AVO#7]
Completely fresh install.

1. Dark Brotherhood Robes Replaced mod, does not work. Vanilla robes show.
2. Ancient Shrouded Armor Replacer mod, does not work, in game assets are invisible.
3. Dark Brotherhood Armor SE mod, shows its inventory for the normal DB shrouded armor.

**Comment by Althro** [comment]
Will be fixed in 5.4 aside from 3 as that's not that easy to resolve. Will attempt though.
