### ISSUE TITLE
[BUG] Stalhrim Refrozen ENB issue

### ISSUE THREAD

**Issue by ellis84** [The-Animonculory/AVO#8]
Stalhrim Refrozen causes the armors to have wierd effects when used with ENB. Apparently something to do with a complex material bug. An apparent fix is here https://www.nexusmods.com/skyrimspecialedition/mods/41348?tab=bugs.

**Comment by Althro** [comment]
Thanks for the report. I'll keep this open as a reminder for myself when I get around to working on updates to fix.

**Comment by Althro** [comment]
Fixed in V6
