### ISSUE TITLE
[BUG] Miraak Armor Mesh/Textures Issues

### ISSUE THREAD

**Issue by ellis84** [The-Animonculory/AVO#9]
Miraak meshes and textures are different between male and females. It also seems to have some kind of mapping issue where it shows up as silver instead of the usual golden colour. Bit of a play around it seems to be an issue with the CBBE/Himbo meshes not working with the Dragonpriest SE mod textures and meshes.

**Comment by Althro** [comment]
This most likely is similar to the issue with Stahlrim Refrozen regarding the textures.

Mesh wise, yes that's likely a body mod issue.

As before, will keep this open till I get to this section on the rework.

**Comment by Althro** [comment]
Fixed in V6
